# Generated by Django 3.1.6 on 2021-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('deptid', models.IntegerField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=30)),
            ],
        ),
    ]
