# Generated by Django 3.1.6 on 2021-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportModel',
            fields=[
                ('sportid', models.IntegerField(primary_key=True, serialize=False)),
                ('sportname', models.CharField(max_length=30)),
                ('sports', models.ManyToManyField(to='cmsapp.StudentModel')),
            ],
        ),
    ]
