# Generated by Django 3.1.6 on 2021-03-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_sportmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportmodel',
            old_name='sports',
            new_name='studentname',
        ),
    ]
