# Generated by Django 3.1.6 on 2021-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_auto_20210328_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportmodel',
            old_name='studentname',
            new_name='sports',
        ),
    ]
