# Generated by Django 3.1.6 on 2021-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_auto_20210329_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportmodel',
            old_name='sports',
            new_name='student',
        ),
    ]
