# Generated by Django 3.1.6 on 2021-03-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_auto_20210329_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cmsapp.studentmodel')),
            ],
        ),
    ]
